server {
    listen 80;
    server_name crowemi;

    access_log /var/log/nginx/crowemi.access.log;
    error_log /var/log/nginx/crowemi.error.log;

    location / {
            include proxy_params;
            proxy_pass http://unix:/app/crowemi.sock;
    }
}