server {
    listen 8080;
    server_name crowemi www.crowemi;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/app/app.sock;
    }
}

server {
    listen 8080;
    server_name localhost;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/app/app.sock;
    }
}

server {
    listen 8080;
    server_name blog.crowemi;

    location / {
        include uwsgi_params;
        uwsgi_pass unix:/app/app.sock;
    }
}